/**
 * ADR-045 §4 — travel_tips tool.
 *
 * Standalone destination advisory: ≤80-char intro + up to 3 iconic places +
 * local transit + aggregated weather + clothing + safety. Reuses
 * findIconicPlaces (grounded when a pool/skeleton is available) and the
 * open-meteo weather adapter with a short-TTL cache.
 *
 * Performance budget (ADR-045 §4.2): a hard 20s outer timeout wraps the whole
 * tool. Inside, the weather and iconic branches run in parallel; each branch
 * has its own inner timeout and degrades on failure (no throw). Only the
 * tips-prose LLM and the outer 20s cap can throw — a timeout surfaces as
 * errors.travel_tips_timeout, other tips-prose failures as
 * errors.travel_tips_failed. LLM calls ≤ 2 (findIconicPlaces + tips-prose).
 *
 * All user-facing prose is generated by the LLM in the requested locale; field
 * labels are i18n keys resolved by the caller. No city POI encyclopedia in
 * source (ADR-042) — iconic names come from LLM weights or the supplied pool.
 */

import { z } from "zod";
import {
  createOpenAI,
  isLlmAbortError,
  withAbortTimeout,
  callItineraryLlmWithValidationRetry,
  type ItineraryChatCreate,
} from "./itinerary-planner";
import { findIconicPlaces } from "./find-iconic-places";
import { getWeatherAdapter } from "../adapters/open-meteo/fixture";
import { aggregatePlanningImpact } from "./travel-weather";
import { cachedWeatherFetch, type WeatherCacheKey, type WeatherForecastValue } from "./weather-cache";
import { geocode } from "./tools";
import { assembleSystemPrompt } from "../agent/prompt-assembler";
import { loadGlossary } from "../agent/loop";
import { t } from "./i18n";
import { parseLocale, type Locale } from "./locales";
import type { ItinerarySkeleton } from "./make-itinerary";
import type { PlaceCard } from "./types";
import type { WeatherSeverity, WeatherDriver } from "./itinerary-weather";

const OUTER_TIMEOUT_MS = 20_000;
const GEOCODE_TIMEOUT_MS = 3_000;
const ICONIC_TIMEOUT_MS = 12_000;
const TIPS_PROSE_TIMEOUT_MS = 10_000;
const INTRO_MAX_CHARS = 80;
const MAX_TRIP_DAYS = 14;

export class TravelTipsTimeoutError extends Error {
  constructor(message = "travel_tips_timeout") {
    super(message);
    this.name = "TravelTipsTimeoutError";
  }
}

export type TravelTipsInput = {
  destination: string;
  /** Inclusive trip date bounds (YYYY-MM-DD); drives multi-day weather aggregation. */
  bounds?: { start: string; end: string };
  trip_type?: string;
  pace?: "tight" | "medium" | "relaxed";
  /** Skeleton from make_itinerary; its attraction stop names seed the iconic pool (方案 A). */
  skeleton?: ItinerarySkeleton;
  /** Free-text planning constraints (party size, interests, etc.). */
  constraints?: string;
  /** Explicit iconic-name pool; skeleton takes precedence when present. */
  pool?: string[];
  locale: Locale;
  providers?: string[];
  /** Test injection for both LLM calls (findIconicPlaces + tips-prose). */
  _testChatCreate?: ItineraryChatCreate;
  /** Test injection to bypass geocode. */
  _testGeo?: { lat: number; lng: number };
};

export type TravelTipsWeather = {
  severity: WeatherSeverity;
  drivers: WeatherDriver[];
  temp_min?: number;
  temp_max?: number;
  summary_key: string;
  summary?: string;
};

export type TravelTipsResult = {
  intro: string;
  iconic_places: string[];
  iconic_grounded: boolean;
  transit: string;
  weather: TravelTipsWeather | null;
  weather_unavailable: boolean;
  clothing: string;
  safety: string;
};

// --- Zod output schema for tips-prose ---

const TipsProseSchema = z.object({
  intro: z.string(),
  transit: z.string(),
  clothing: z.string(),
  safety: z.string(),
});

type TipsProse = z.infer<typeof TipsProseSchema>;

// --- Weather fetch cache (module-level, 30 min TTL) ---

const cachedForecast = cachedWeatherFetch(async (key: WeatherCacheKey): Promise<WeatherForecastValue | null> => {
  const adapter = getWeatherAdapter();
  const f = await adapter.fetchForecast({ lat: key.lat, lng: key.lng, date: key.date });
  if (!f) return null;
  return {
    weather_code: f.weather_code,
    temp_max_c: f.temp_max_c,
    temp_min_c: f.temp_min_c,
    provider: f.provider,
  };
});

// --- Helpers ---

function buildCreate(input: TravelTipsInput): ItineraryChatCreate | null {
  if (input._testChatCreate) return input._testChatCreate;
  const openai = createOpenAI();
  if (!openai) return null;
  return openai.chat.completions.create.bind(openai.chat.completions) as unknown as ItineraryChatCreate;
}

function todayDate(): string {
  return new Date().toISOString().slice(0, 10);
}

/** Inclusive YYYY-MM-DD list from bounds, capped at MAX_TRIP_DAYS. */
function enumerateDates(bounds: { start: string; end: string }): string[] {
  const start = new Date(`${bounds.start}T00:00:00Z`);
  const end = new Date(`${bounds.end}T00:00:00Z`);
  if (Number.isNaN(start.getTime()) || Number.isNaN(end.getTime()) || end < start) {
    return [bounds.start];
  }
  const out: string[] = [];
  const cursor = new Date(start);
  while (cursor <= end && out.length < MAX_TRIP_DAYS) {
    out.push(cursor.toISOString().slice(0, 10));
    cursor.setUTCDate(cursor.getUTCDate() + 1);
  }
  return out;
}

/** Extract attraction stop names from a skeleton (方案 A, pure data, no LLM). */
function poolFromSkeleton(skeleton: ItinerarySkeleton | undefined): string[] {
  if (!skeleton) return [];
  const names: string[] = [];
  for (const day of skeleton.days) {
    for (const stop of day.stops) {
      if (stop.kind === "attraction" && stop.name) names.push(stop.name);
    }
  }
  return names;
}

function localeLanguage(locale: Locale): string {
  switch (locale) {
    case "CN":
      return "Simplified Chinese (简体中文)";
    case "HK":
      return "Traditional Chinese (香港繁體)";
    case "TW":
      return "Traditional Chinese (台灣繁體)";
    default:
      return "English";
  }
}

function weatherContext(weather: TravelTipsWeather | null): string {
  if (!weather) return "Weather: unavailable.";
  const drivers = weather.drivers.length > 0 ? weather.drivers.join(", ") : "clear";
  const lo = weather.temp_min != null ? `${weather.temp_min}°C` : "?";
  const hi = weather.temp_max != null ? `${weather.temp_max}°C` : "?";
  return `Aggregated weather — severity: ${weather.severity}; drivers: ${drivers}; temp range: low ${lo} / high ${hi}.`;
}

// --- Branches ---

async function weatherBranch(input: TravelTipsInput): Promise<TravelTipsWeather | null> {
  try {
    let lat: number | undefined = input._testGeo?.lat;
    let lng: number | undefined = input._testGeo?.lng;
    if (lat == null || lng == null) {
      const geo = await Promise.race([
        geocode({ query: input.destination, locale: input.locale, providers: input.providers }),
        new Promise<null>((resolve) => setTimeout(() => resolve(null), GEOCODE_TIMEOUT_MS)),
      ]);
      lat = geo?.data?.lat;
      lng = geo?.data?.lng;
    }
    if (lat == null || lng == null) return null;

    const dates =
      input.bounds && input.bounds.start && input.bounds.end
        ? enumerateDates(input.bounds)
        : [todayDate()];

    const forecasts: WeatherForecastValue[] = [];
    for (const date of dates) {
      const f = await cachedForecast({ lat, lng, date });
      if (f) forecasts.push(f);
    }
    if (forecasts.length === 0) return null;

    const agg = aggregatePlanningImpact(
      forecasts.map((f) => ({
        weather_code: f.weather_code,
        temp_max_c: f.temp_max_c,
        temp_min_c: f.temp_min_c,
        provider: "OPEN_METEO",
      })),
    );
    return {
      severity: agg.severity,
      drivers: agg.drivers,
      temp_min: agg.temp_min,
      temp_max: agg.temp_max,
      summary_key: `itinerary.weather.impact_${agg.severity}`,
      summary: t(input.locale, `itinerary.weather.impact_${agg.severity}`),
    };
  } catch (err) {
    console.error("travelTips: weather branch failed, degrading to null", err);
    return null;
  }
}

async function iconicBranch(
  input: TravelTipsInput,
  pool: string[],
): Promise<{ names: string[]; grounded: boolean }> {
  try {
    return await Promise.race([
      findIconicPlaces({
        city: input.destination,
        locale: input.locale,
        limit: 3,
        pool: pool.length > 0 ? poolToCards(pool) : undefined,
        _testChatCreate: input._testChatCreate,
      }),
      new Promise<{ names: string[]; grounded: boolean }>((resolve) =>
        setTimeout(
          () => resolve({ names: [], grounded: false }),
          ICONIC_TIMEOUT_MS,
        ),
      ),
    ]);
  } catch (err) {
    console.error("travelTips: iconic branch failed, degrading", err);
    return { names: [], grounded: false };
  }
}

/** findIconicPlaces expects PlaceCard[]; wrap raw names minimally (only .name is read). */
function poolToCards(names: string[]): PlaceCard[] {
  return names.map((n) => ({
    provider: "GOOGLE_MAPS",
    name: n,
    location: { lat: 0, lng: 0, crs: "WGS84" },
    sources: [],
  }));
}

async function tipsProseLlm(
  input: TravelTipsInput,
  create: ItineraryChatCreate,
  weather: TravelTipsWeather | null,
  iconic: { names: string[]; grounded: boolean },
): Promise<TipsProse> {
  const locale = parseLocale(input.locale);
  const systemPrompt = assembleSystemPrompt({
    locale,
    intent: "travel-tips",
    glossary: loadGlossary(locale) ?? undefined,
  });

  const ctxParts: string[] = [
    `Destination: ${input.destination}`,
    `Iconic places (use ONLY these in iconic_places; if empty, omit specific names): ${JSON.stringify(iconic.names)}`,
    weatherContext(weather),
  ];
  if (input.trip_type) ctxParts.push(`Trip type: ${input.trip_type}`);
  if (input.pace) ctxParts.push(`Pace: ${input.pace}`);
  if (input.constraints) ctxParts.push(`Constraints: ${input.constraints}`);
  ctxParts.push(`Write every field in ${localeLanguage(locale)}.`);

  const userMessage =
    `Return ONLY a JSON object with fields: ` +
    `"intro" (destination overview, ≤ ${INTRO_MAX_CHARS} characters), ` +
    `"transit" (local transit advice, 1–2 sentences), ` +
    `"clothing" (what to wear/pack for the weather above, 1–2 sentences), ` +
    `"safety" (safety reminder, 1–2 sentences). ` +
    `Do not invent itineraries or restaurant names.\n${ctxParts.join("\n")}`;

  try {
    return await callItineraryLlmWithValidationRetry<TipsProse>({
      create,
      systemPrompt,
      userMessage,
      timeoutMs: TIPS_PROSE_TIMEOUT_MS,
      temperature: 0.4,
      maxCompletionTokens: 900,
      failLabel: "travel_tips_failed",
      parseAndValidate: (raw) => {
        const json = JSON.parse(raw);
        const parsed = TipsProseSchema.safeParse(json);
        if (parsed.success) return { ok: true, value: { ...parsed.data, intro: parsed.data.intro.slice(0, INTRO_MAX_CHARS) } };
        return { ok: false, error: parsed.error.issues.map((i) => `${i.path.join(".")}: ${i.message}`).join("; "), retryable: true };
      },
    });
  } catch (err) {
    if (err instanceof TravelTipsTimeoutError) throw err;
    if (isLlmAbortError(err) || isLlmAbortError((err as Error)?.cause)) {
      throw new TravelTipsTimeoutError();
    }
    // Validation failure after retry → surface as a failed (non-timeout) error.
    throw err;
  }
}

// --- Main entry ---

export async function travelTips(input: TravelTipsInput): Promise<TravelTipsResult> {
  // 方案 A: skeleton attraction names seed the iconic pool; skeleton takes
  // precedence over an explicit pool.
  const pool = poolFromSkeleton(input.skeleton).length > 0
    ? poolFromSkeleton(input.skeleton)
    : input.pool ?? [];

  // Fixture/no-key mode: cannot run the tips-prose LLM. Return iconic + weather
  // (degraded) without a prose call.
  const create = buildCreate(input);
  const fixtureMode = !input._testChatCreate && createOpenAI() === null;

  try {
    return await withAbortTimeout(OUTER_TIMEOUT_MS, async () => {
      const [weather, iconic] = await Promise.all([
        weatherBranch(input),
        iconicBranch(input, pool),
      ]);

      if (fixtureMode || !create) {
        return {
          intro: "",
          iconic_places: iconic.names,
          iconic_grounded: iconic.grounded,
          transit: "",
          weather,
          weather_unavailable: weather === null,
          clothing: "",
          safety: "",
        };
      }

      const prose = await tipsProseLlm(input, create, weather, iconic);
      return {
        intro: prose.intro,
        iconic_places: iconic.names,
        iconic_grounded: iconic.grounded,
        transit: prose.transit,
        weather,
        weather_unavailable: weather === null,
        clothing: prose.clothing,
        safety: prose.safety,
      };
    });
  } catch (err) {
    if (err instanceof TravelTipsTimeoutError) throw err;
    if (isLlmAbortError(err) || isLlmAbortError((err as Error)?.cause)) {
      throw new TravelTipsTimeoutError();
    }
    throw err;
  }
}
